version: ""
formatter: 

header-from: main.tf
footer-from: ""

sections:
    hide: []
    show: []

    hide-all: false
    show-all: true

content: ""

output:
    file: ""
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->

output-values:
    enabled: false
    from: ""

sort:
    enabled: true
    by: name

settings:
    anchor: true
    color: true
    default: true
    description: false
    escape: true
    html: true
    indent: 2
    lockfile: true
    required: true
    sensitive: true
    type: true